// Brand colors composed from the design system (@mkdigitalsk/design-system), not defined here.
// Material-3 container/surface extras are derived from brand primitives.
import { Brand, Light, Dark } from '@mkdigitalsk/design-system';

export const lightColorScheme = {
  primary: Light.primary,
  onPrimary: '#FFFFFF',
  primaryContainer: Brand.blue,
  onPrimaryContainer: '#FFFFFF',
  secondary: Light.secondary,
  onSecondary: '#FFFFFF',
  secondaryContainer: Brand.tealDark,
  onSecondaryContainer: '#FFFFFF',
  background: Light.neutral[0],
  onBackground: Light.neutral[80],
  surface: Light.neutral[0],
  onSurface: Light.neutral[80],
  error: Light.error,
  onError: '#FFFFFF',
  errorContainer: '#F9DEDC',
  onErrorContainer: '#FFFFFF',
  surfaceTint: Light.primary,
  surfaceVariant: '#E4E4E4',
  onSurfaceVariant: '#49454F',
  outline: '#79747E',
  outlineVariant: '#CAC4D0',
  // Custom colors
  neutral0: Light.neutral[0],
  neutral10: '#E4E4E4',
  neutral20: Light.neutral[20],
  neutral40: Light.neutral[40],
  neutral60: Light.neutral[60],
  neutral80: Light.neutral[80],
  neutral100: Light.neutral[100],
  brandBar: Light.brandBar,
  onBrandBar: Light.onBrandBar,
  success: Light.success,
  warning: Light.warning,
  transparent: '#00000000',
} as const;

export const darkColorScheme = {
  primary: Dark.primary,
  onPrimary: '#121212',
  primaryContainer: Brand.navy,
  onPrimaryContainer: '#FFFFFF',
  secondary: Dark.secondary,
  onSecondary: '#121212',
  secondaryContainer: Brand.tealDark,
  onSecondaryContainer: '#121212',
  background: Dark.neutral[0],
  onBackground: Dark.neutral[100],
  surface: '#1E1E1E',
  onSurface: Dark.neutral[100],
  error: Dark.error,
  onError: '#121212',
  errorContainer: '#93000A',
  onErrorContainer: '#FFFFFF',
  surfaceTint: Dark.primary,
  surfaceVariant: '#49454F',
  onSurfaceVariant: '#CAC4D0',
  outline: '#938F99',
  outlineVariant: '#49454F',
  // Custom colors
  neutral0: Dark.neutral[0],
  neutral10: '#1F1F1F',
  neutral20: Dark.neutral[20],
  neutral40: Dark.neutral[40],
  neutral60: Dark.neutral[60],
  neutral80: Dark.neutral[80],
  neutral100: Dark.neutral[100],
  brandBar: Dark.brandBar,
  onBrandBar: Dark.onBrandBar,
  success: Dark.success,
  warning: Dark.warning,
  transparent: '#00000000',
} as const;
