export const en = {
  // Navigation
  nav_home: 'Home',
  nav_settings: 'Settings',

  // Screens
  screen_home: 'Home',
  screen_ui_components: 'UI Components',
  screen_networking: 'Networking',
  screen_storage: 'Storage',
  screen_database: 'Database',
  screen_platform_apis: 'Platform APIs',
  screen_scanner: 'Scanner',
  screen_calendar: 'Calendar',
  screen_notifications: 'Notifications',
  screen_settings: 'Settings',

  // Feature subtitles (Home screen cards)
  feature_ui_components_subtitle: 'Material Design 3 components',
  feature_networking_subtitle: 'REST API integration with Axios',
  feature_storage_subtitle: 'Local storage with MMKV',
  feature_database_subtitle: 'SQLite database integration',
  feature_platform_apis_subtitle: 'Native platform integrations',
  feature_scanner_subtitle: 'QR code and barcode scanning',
  feature_calendar_subtitle: 'Calendar events integration',
  feature_notifications_subtitle: 'Push and local notifications',

  // UI Components
  ui_section_buttons: 'Buttons',
  ui_contained_button: 'Contained Button',
  ui_outlined_button: 'Outlined Button',
  ui_text_button: 'Text Button',
  ui_error_text_button: 'Error Text Button',
  ui_section_segmented: 'Segmented Button',
  ui_segment_day: 'Day',
  ui_segment_week: 'Week',
  ui_segment_month: 'Month',
  ui_section_typography: 'Typography',
  ui_headline_medium: 'Headline Medium',
  ui_title_large: 'Title Large',
  ui_body_large: 'Body Large',
  ui_body_medium: 'Body Medium',
  ui_body_small: 'Body Small',
  ui_label_large: 'Label Large',
  ui_label_medium: 'Label Medium',
  ui_section_cards: 'Cards',
  ui_elevated_card: 'Elevated Card (clickable)',
  ui_contained_card: 'Contained Card (clickable)',
  ui_section_text_fields: 'Text Fields',
  ui_text_field_label: 'Label',
  ui_text_field_placeholder: 'Type something...',
  ui_section_checkbox: 'Checkbox',
  ui_checked: 'Checked',
  ui_unchecked: 'Unchecked',
  ui_section_switch: 'Switch',
  ui_on: 'On',
  ui_off: 'Off',
  ui_section_radio: 'Radio Buttons',
  ui_option_1: 'Option 1',
  ui_option_2: 'Option 2',
  ui_option_3: 'Option 3',
  ui_section_chips: 'Chips',
  ui_filter_1: 'Filter 1',
  ui_filter_2: 'Filter 2',
  ui_filter_3: 'Filter 3',
  ui_chip_assist: 'Assist',
  ui_chip_input: 'Input',
  ui_chip_suggestion: 'Suggestion',
  ui_section_slider: 'Slider',
  ui_section_divider: 'Divider',
  ui_section_loading: 'Loading & Progress',
  ui_section_badges: 'Badges',
  ui_section_snackbar: 'Snackbar',
  ui_snackbar_default: 'Default',
  ui_snackbar_default_message: 'Default snackbar',
  ui_snackbar_success: 'Success',
  ui_snackbar_success_message: 'Success!',
  ui_snackbar_error: 'Error',
  ui_snackbar_error_message: 'Error occurred',
  ui_snackbar_warning: 'Warning',
  ui_snackbar_warning_message: 'Warning!',
  ui_section_bottom_sheet: 'Bottom Sheet',
  ui_show_bottom_sheet: 'Show Bottom Sheet',
  ui_bottom_sheet_title: 'Bottom Sheet',
  ui_bottom_sheet_content: 'This is a bottom sheet content area.',
  ui_close: 'Close',
  ui_section_dialog: 'Dialog',
  ui_show_dialog: 'Show Dialog',
  ui_dialog_title: 'Confirm',
  ui_dialog_text: 'This is a confirm dialog example.',

  // Settings
  settings_language: 'Language',
  settings_theme: 'Theme',
  settings_dark_mode: 'Dark Mode',
  settings_about: 'About',
  settings_version: 'Version',
  settings_appearance: 'Appearance',
  settings_theme_light: 'Light',
  settings_theme_dark: 'Dark',
  settings_theme_system: 'System',

  // Languages
  language_en: 'English',
  language_sk: 'Slovak',

  // Storage
  storage_title: 'Local Storage',
  storage_subtitle: 'Demonstrates session vs persistent storage using MMKV',
  storage_session_label: 'Session Counter',
  storage_session_hint: 'Resets when app is killed or session is cleared',
  storage_persistent_label: 'Persistent Counter',
  storage_persistent_hint: 'Survives app restarts (stored in MMKV)',
  storage_clear_session: 'Clear Session',

  // Platform APIs
  platform_apis_title: 'Platform APIs',
  platform_apis_subtitle: 'Native platform integrations and device features',
  platform_apis_share_title: 'Share',
  platform_apis_share_action: 'Share Text',
  platform_apis_dial_title: 'Phone Dialer',
  platform_apis_dial_action: 'Dial Number',
  platform_apis_link_title: 'Open Link',
  platform_apis_link_action: 'Open in Browser',
  platform_apis_email_title: 'Send Email',
  platform_apis_email_action: 'Compose Email',
  platform_apis_copy_title: 'Clipboard',
  platform_apis_copy_action: 'Copy to Clipboard',
  platform_apis_copied_message: 'Copied to clipboard',
  platform_apis_location_title: 'Location',
  platform_apis_location_action: 'Get Location',
  platform_apis_location_loading: 'Getting location...',
  platform_apis_location_error: 'Failed to get location',
  platform_apis_location_result: 'Lat: %s, Lon: %s',
  platform_apis_location_updates_title: 'Location Updates',
  platform_apis_location_updates_start: 'Start Tracking',
  platform_apis_location_updates_stop: 'Stop Tracking',
  platform_apis_location_updates_error: 'Location tracking failed',
  platform_apis_biometrics_title: 'Biometrics',
  platform_apis_biometrics_action: 'Authenticate',
  platform_apis_biometrics_success: 'Authentication successful',
  platform_apis_biometrics_failed: 'Authentication failed',
  platform_apis_biometrics_cancelled: 'Authentication cancelled',
  platform_apis_biometrics_not_available: 'Biometrics not available',
  platform_apis_flashlight_title: 'Flashlight',
  platform_apis_flashlight_on: 'Turn On',
  platform_apis_flashlight_off: 'Turn Off',
  platform_apis_flashlight_not_available: 'Flashlight not available',

  // Database
  database_title: 'Database',
  database_subtitle: 'SQLite database with CRUD operations, search, and sorting',
  database_search_placeholder: 'Search notes...',
  database_sort_date_desc: 'Newest first',
  database_sort_date_asc: 'Oldest first',
  database_sort_title_asc: 'Title A-Z',
  database_sort_title_desc: 'Title Z-A',
  database_add_title_placeholder: 'Note title',
  database_add_content_placeholder: 'Note content',
  database_add_button: 'Add Note',
  database_delete_all: 'Clear All',
  database_empty: 'No notes yet. Add your first note above.',
  database_no_results: 'No notes match your search.',

  // Scanner
  scanner_title: 'Scanner',
  scanner_subtitle: 'QR code and barcode scanning and generation',
  scanner_mode_generate: 'Generate',
  scanner_mode_scan: 'Scan',
  scanner_format_qr: 'QR Code',
  scanner_format_barcode: 'Barcode',
  scanner_input_placeholder: 'Enter text to generate code',
  scanner_generate_button: 'Generate',
  scanner_scanned_result: 'Scanned result',
  scanner_clear_result: 'Clear',
  scanner_no_camera: 'No camera device found',
  scanner_permission_denied: 'Camera permission denied',
  scanner_request_permission: 'Grant permission',

  // Calendar
  calendar_title: 'Calendar',
  calendar_subtitle: 'Date range picker with disabled dates and selection validation',
  calendar_selected_range: 'Selected range',
  calendar_start_date: 'Start',
  calendar_end_date: 'End',
  calendar_clear_selection: 'Clear selection',
  calendar_no_selection: 'Tap a date to start selecting a range',
  calendar_disabled_in_range: 'Range contains disabled dates, selection reset',

  // Notifications
  notifications_title: 'Notifications',
  notifications_subtitle: 'Local notifications with channels, permissions, and settings',
  notifications_permission_title: 'Permission',
  notifications_permission_granted: 'Notification permission granted',
  notifications_permission_denied: 'Notification permission denied',
  notifications_permission_unknown: 'Permission not yet requested',
  notifications_request_permission: 'Request Permission',
  notifications_send_title: 'Send Notifications',
  notifications_last_sent: 'Last sent',
  notifications_send_reminder: 'Reminder',
  notifications_send_promo: 'Promo',
  notifications_reminder_title: 'Reminder',
  notifications_reminder_message: 'Don\'t forget to check your tasks!',
  notifications_promo_title: 'Special Offer',
  notifications_promo_message: 'Check out our latest deals and updates!',
  notifications_cancel_title: 'Manage',
  notifications_open_settings: 'Settings',
  notifications_cancel_all: 'Cancel All',

  // Login
  login_title: 'Welcome',
  login_subtitle: 'Sign in to continue',
  login_email_label: 'Email',
  login_email_placeholder: 'Enter your email',
  login_password_label: 'Password',
  login_password_placeholder: 'Enter your password',
  login_button: 'Sign In',
  login_skip: 'Skip',
  login_fill_test: 'Fill Test Account',
  login_biometric_label: 'Sign in with biometrics',
  login_biometric_cancelled: 'Authentication cancelled',
  login_email_error_empty: 'Email is required',
  login_email_error_invalid: 'Invalid email format',
  login_password_error_empty: 'Password is required',
  login_password_error_short: 'Password must be at least 8 characters',
  login_password_error_weak: 'Password must contain uppercase, lowercase, digit, and special character',
  login_to_register: 'Don\'t have an account? Register',

  // Register
  register_title: 'Create Account',
  register_subtitle: 'Fill in your details to register',
  register_name_label: 'Name',
  register_name_placeholder: 'Enter your name',
  register_email_label: 'Email',
  register_email_placeholder: 'Enter your email',
  register_password_label: 'Password',
  register_password_placeholder: 'Enter your password',
  register_confirm_label: 'Confirm Password',
  register_confirm_placeholder: 'Confirm your password',
  register_button: 'Register',
  register_to_login: 'Already have an account? Sign in',
  register_name_error_empty: 'Name is required',
  register_email_error_empty: 'Email is required',
  register_email_error_invalid: 'Invalid email format',
  register_email_error_already_exists: 'This email is already registered',
  register_password_error_empty: 'Password is required',
  register_password_error_short: 'Password must be at least 8 characters',
  register_password_error_weak: 'Password must contain uppercase, lowercase, digit, and special character',
  register_confirm_error_empty: 'Please confirm your password',
  register_confirm_error_mismatch: 'Passwords do not match',

  // Common
  common_loading: 'Loading...',
  common_error: 'Error',
  common_retry: 'Retry',
  common_cancel: 'Cancel',
  common_ok: 'OK',
  common_save: 'Save',
} as const;

export type StringKey = keyof typeof en;
