export const en = {
  // Navigation
  nav_home: 'Home',
  nav_settings: 'Settings',

  // Screens
  screen_home: 'Home',
  screen_ui_components: 'UI Components',
  screen_networking: 'Networking',
  screen_storage: 'Storage',
  screen_settings: 'Settings',

  // Settings
  settings_language: 'Language',
  settings_theme: 'Theme',
  settings_dark_mode: 'Dark Mode',
  settings_about: 'About',
  settings_version: 'Version',
  settings_appearance: 'Appearance',
  settings_theme_light: 'Light',
  settings_theme_dark: 'Dark',
  settings_theme_system: 'System',

  // Languages
  language_en: 'English',
  language_sk: 'Slovak',

  // Storage
  storage_title: 'Local Storage',
  storage_subtitle: 'Demonstrates session vs persistent storage using MMKV',
  storage_session_label: 'Session Counter',
  storage_session_hint: 'Resets when app is killed or session is cleared',
  storage_persistent_label: 'Persistent Counter',
  storage_persistent_hint: 'Survives app restarts (stored in MMKV)',
  storage_clear_session: 'Clear Session',

  // Platform APIs
  platform_apis_title: 'Platform APIs',
  platform_apis_subtitle: 'Native platform integrations and device features',
  platform_apis_share_title: 'Share',
  platform_apis_share_action: 'Share Text',
  platform_apis_dial_title: 'Phone Dialer',
  platform_apis_dial_action: 'Dial Number',
  platform_apis_link_title: 'Open Link',
  platform_apis_link_action: 'Open in Browser',
  platform_apis_email_title: 'Send Email',
  platform_apis_email_action: 'Compose Email',
  platform_apis_copy_title: 'Clipboard',
  platform_apis_copy_action: 'Copy to Clipboard',
  platform_apis_copied_message: 'Copied to clipboard',
  platform_apis_location_title: 'Location',
  platform_apis_location_action: 'Get Location',
  platform_apis_location_loading: 'Getting location...',
  platform_apis_location_error: 'Failed to get location',
  platform_apis_location_result: 'Lat: %s, Lon: %s',
  platform_apis_location_updates_title: 'Location Updates',
  platform_apis_location_updates_start: 'Start Tracking',
  platform_apis_location_updates_stop: 'Stop Tracking',
  platform_apis_location_updates_error: 'Location tracking failed',
  platform_apis_biometrics_title: 'Biometrics',
  platform_apis_biometrics_action: 'Authenticate',
  platform_apis_biometrics_success: 'Authentication successful',
  platform_apis_biometrics_failed: 'Authentication failed',
  platform_apis_biometrics_cancelled: 'Authentication cancelled',
  platform_apis_biometrics_not_available: 'Biometrics not available',
  platform_apis_flashlight_title: 'Flashlight',
  platform_apis_flashlight_on: 'Turn On',
  platform_apis_flashlight_off: 'Turn Off',
  platform_apis_flashlight_not_available: 'Flashlight not available',

  // Database
  database_title: 'Database',
  database_subtitle: 'SQLite database with CRUD operations, search, and sorting',
  database_search_placeholder: 'Search notes...',
  database_sort_date_desc: 'Newest first',
  database_sort_date_asc: 'Oldest first',
  database_sort_title_asc: 'Title A-Z',
  database_sort_title_desc: 'Title Z-A',
  database_add_title_placeholder: 'Note title',
  database_add_content_placeholder: 'Note content',
  database_add_button: 'Add Note',
  database_delete_all: 'Clear All',
  database_empty: 'No notes yet. Add your first note above.',
  database_no_results: 'No notes match your search.',

  // Scanner
  scanner_title: 'Scanner',
  scanner_subtitle: 'QR code and barcode scanning and generation',
  scanner_mode_generate: 'Generate',
  scanner_mode_scan: 'Scan',
  scanner_format_qr: 'QR Code',
  scanner_format_barcode: 'Barcode',
  scanner_input_placeholder: 'Enter text to generate code',
  scanner_generate_button: 'Generate',
  scanner_scanned_result: 'Scanned result',
  scanner_clear_result: 'Clear',
  scanner_no_camera: 'No camera device found',
  scanner_permission_denied: 'Camera permission denied',
  scanner_request_permission: 'Grant permission',

  // Calendar
  calendar_title: 'Calendar',
  calendar_subtitle: 'Date range picker with disabled dates and selection validation',
  calendar_selected_range: 'Selected range',
  calendar_start_date: 'Start',
  calendar_end_date: 'End',
  calendar_clear_selection: 'Clear selection',
  calendar_no_selection: 'Tap a date to start selecting a range',
  calendar_disabled_in_range: 'Range contains disabled dates, selection reset',

  // Common
  common_loading: 'Loading...',
  common_error: 'Error',
  common_retry: 'Retry',
  common_cancel: 'Cancel',
  common_ok: 'OK',
  common_save: 'Save',
} as const;

export type StringKey = keyof typeof en;
