import { StringKey } from './en';

export const sk: Record<StringKey, string> = {
  // Navigation
  nav_home: 'Domov',
  nav_settings: 'Nastavenia',

  // Screens
  screen_home: 'Domov',
  screen_ui_components: 'UI Komponenty',
  screen_networking: 'Sieť',
  screen_storage: 'Úložisko',
  screen_database: 'Databáza',
  screen_platform_apis: 'Platformové API',
  screen_scanner: 'Skener',
  screen_calendar: 'Kalendár',
  screen_notifications: 'Notifikácie',
  screen_settings: 'Nastavenia',

  // Feature subtitles (Home screen cards)
  feature_ui_components_subtitle: 'Material Design 3 komponenty',
  feature_networking_subtitle: 'REST API integrácia s Axios',
  feature_storage_subtitle: 'Lokálne úložisko s MMKV',
  feature_database_subtitle: 'SQLite databázová integrácia',
  feature_platform_apis_subtitle: 'Natívne platformové integrácie',
  feature_scanner_subtitle: 'Skenovanie QR a čiarových kódov',
  feature_calendar_subtitle: 'Integrácia kalendárových udalostí',
  feature_notifications_subtitle: 'Push a lokálne notifikácie',

  // UI Components
  ui_section_buttons: 'Tlačidlá',
  ui_contained_button: 'Vyplnené tlačidlo',
  ui_outlined_button: 'Obrysové tlačidlo',
  ui_text_button: 'Textové tlačidlo',
  ui_error_text_button: 'Chybové textové tlačidlo',
  ui_section_segmented: 'Segmentové tlačidlo',
  ui_segment_day: 'Deň',
  ui_segment_week: 'Týždeň',
  ui_segment_month: 'Mesiac',
  ui_section_typography: 'Typografia',
  ui_headline_medium: 'Headline Medium',
  ui_title_large: 'Title Large',
  ui_body_large: 'Body Large',
  ui_body_medium: 'Body Medium',
  ui_body_small: 'Body Small',
  ui_label_large: 'Label Large',
  ui_label_medium: 'Label Medium',
  ui_section_cards: 'Karty',
  ui_elevated_card: 'Vyvýšená karta (klikateľná)',
  ui_contained_card: 'Vyplnená karta (klikateľná)',
  ui_section_text_fields: 'Textové polia',
  ui_text_field_label: 'Popis',
  ui_text_field_placeholder: 'Napíšte niečo...',
  ui_section_checkbox: 'Zaškrtávacie pole',
  ui_checked: 'Zaškrtnuté',
  ui_unchecked: 'Nezaškrtnuté',
  ui_section_switch: 'Prepínač',
  ui_on: 'Zapnuté',
  ui_off: 'Vypnuté',
  ui_section_radio: 'Prepínacie tlačidlá',
  ui_option_1: 'Možnosť 1',
  ui_option_2: 'Možnosť 2',
  ui_option_3: 'Možnosť 3',
  ui_section_chips: 'Čipy',
  ui_filter_1: 'Filter 1',
  ui_filter_2: 'Filter 2',
  ui_filter_3: 'Filter 3',
  ui_chip_assist: 'Pomoc',
  ui_chip_input: 'Vstup',
  ui_chip_suggestion: 'Návrh',
  ui_section_slider: 'Posuvník',
  ui_section_divider: 'Oddeľovač',
  ui_section_loading: 'Načítavanie a priebeh',
  ui_section_badges: 'Odznaky',
  ui_section_snackbar: 'Snackbar',
  ui_snackbar_default: 'Predvolené',
  ui_snackbar_default_message: 'Predvolený snackbar',
  ui_snackbar_success: 'Úspech',
  ui_snackbar_success_message: 'Úspech!',
  ui_snackbar_error: 'Chyba',
  ui_snackbar_error_message: 'Vyskytla sa chyba',
  ui_snackbar_warning: 'Upozornenie',
  ui_snackbar_warning_message: 'Upozornenie!',
  ui_section_bottom_sheet: 'Spodný panel',
  ui_show_bottom_sheet: 'Zobraziť spodný panel',
  ui_bottom_sheet_title: 'Spodný panel',
  ui_bottom_sheet_content: 'Toto je obsah spodného panela.',
  ui_close: 'Zavrieť',
  ui_section_dialog: 'Dialóg',
  ui_show_dialog: 'Zobraziť dialóg',
  ui_dialog_title: 'Potvrdenie',
  ui_dialog_text: 'Toto je príklad potvrdzovacieho dialógu.',

  // Settings
  settings_language: 'Jazyk',
  settings_theme: 'Téma',
  settings_dark_mode: 'Tmavý režim',
  settings_about: 'O aplikácii',
  settings_version: 'Verzia',
  settings_appearance: 'Vzhľad',
  settings_theme_light: 'Svetlý',
  settings_theme_dark: 'Tmavý',
  settings_theme_system: 'Systém',

  // Languages
  language_en: 'Angličtina',
  language_sk: 'Slovenčina',

  // Storage
  storage_title: 'Lokálne úložisko',
  storage_subtitle: 'Demonštrácia session vs perzistentného úložiska pomocou MMKV',
  storage_session_label: 'Session počítadlo',
  storage_session_hint: 'Resetuje sa pri zatvorení aplikácie alebo vyčistení session',
  storage_persistent_label: 'Perzistentné počítadlo',
  storage_persistent_hint: 'Prežije reštart aplikácie (uložené v MMKV)',
  storage_clear_session: 'Vyčistiť session',

  // Platform APIs
  platform_apis_title: 'Platformové API',
  platform_apis_subtitle: 'Natívne integrácie a funkcie zariadenia',
  platform_apis_share_title: 'Zdieľanie',
  platform_apis_share_action: 'Zdieľať text',
  platform_apis_dial_title: 'Telefón',
  platform_apis_dial_action: 'Vytočiť číslo',
  platform_apis_link_title: 'Otvoriť odkaz',
  platform_apis_link_action: 'Otvoriť v prehliadači',
  platform_apis_email_title: 'Odoslať email',
  platform_apis_email_action: 'Napísať email',
  platform_apis_copy_title: 'Schránka',
  platform_apis_copy_action: 'Kopírovať do schránky',
  platform_apis_copied_message: 'Skopírované do schránky',
  platform_apis_location_title: 'Poloha',
  platform_apis_location_action: 'Získať polohu',
  platform_apis_location_loading: 'Získavam polohu...',
  platform_apis_location_error: 'Nepodarilo sa získať polohu',
  platform_apis_location_result: 'Lat: %s, Lon: %s',
  platform_apis_location_updates_title: 'Sledovanie polohy',
  platform_apis_location_updates_start: 'Spustiť sledovanie',
  platform_apis_location_updates_stop: 'Zastaviť sledovanie',
  platform_apis_location_updates_error: 'Sledovanie polohy zlyhalo',
  platform_apis_biometrics_title: 'Biometria',
  platform_apis_biometrics_action: 'Autentifikovať',
  platform_apis_biometrics_success: 'Autentifikácia úspešná',
  platform_apis_biometrics_failed: 'Autentifikácia zlyhala',
  platform_apis_biometrics_cancelled: 'Autentifikácia zrušená',
  platform_apis_biometrics_not_available: 'Biometria nie je dostupná',
  platform_apis_flashlight_title: 'Baterka',
  platform_apis_flashlight_on: 'Zapnúť',
  platform_apis_flashlight_off: 'Vypnúť',
  platform_apis_flashlight_not_available: 'Baterka nie je dostupná',

  // Database
  database_title: 'Databáza',
  database_subtitle: 'SQLite databáza s CRUD operáciami, vyhľadávaním a triedením',
  database_search_placeholder: 'Hľadať poznámky...',
  database_sort_date_desc: 'Najnovšie',
  database_sort_date_asc: 'Najstaršie',
  database_sort_title_asc: 'Názov A-Z',
  database_sort_title_desc: 'Názov Z-A',
  database_add_title_placeholder: 'Názov poznámky',
  database_add_content_placeholder: 'Obsah poznámky',
  database_add_button: 'Pridať poznámku',
  database_delete_all: 'Vymazať všetko',
  database_empty: 'Žiadne poznámky. Pridajte prvú poznámku vyššie.',
  database_no_results: 'Žiadne poznámky nezodpovedajú vyhľadávaniu.',

  // Scanner
  scanner_title: 'Skener',
  scanner_subtitle: 'Skenovanie a generovanie QR kódov a čiarových kódov',
  scanner_mode_generate: 'Generovať',
  scanner_mode_scan: 'Skenovať',
  scanner_format_qr: 'QR kód',
  scanner_format_barcode: 'Čiarový kód',
  scanner_input_placeholder: 'Zadajte text pre generovanie kódu',
  scanner_generate_button: 'Generovať',
  scanner_scanned_result: 'Výsledok skenovania',
  scanner_clear_result: 'Vyčistiť',
  scanner_no_camera: 'Kamera nebola nájdená',
  scanner_permission_denied: 'Prístup ku kamere zamietnutý',
  scanner_request_permission: 'Povoliť prístup',

  // Calendar
  calendar_title: 'Kalendár',
  calendar_subtitle: 'Výber rozsahu dátumov s deaktivovanými dňami a validáciou',
  calendar_selected_range: 'Vybraný rozsah',
  calendar_start_date: 'Začiatok',
  calendar_end_date: 'Koniec',
  calendar_clear_selection: 'Zrušiť výber',
  calendar_no_selection: 'Ťuknite na dátum pre začatie výberu rozsahu',
  calendar_disabled_in_range: 'Rozsah obsahuje deaktivované dátumy, výber resetovaný',

  // Notifications
  notifications_title: 'Notifikácie',
  notifications_subtitle: 'Lokálne notifikácie s kanálmi, povoleniami a nastaveniami',
  notifications_permission_title: 'Povolenie',
  notifications_permission_granted: 'Povolenie pre notifikácie udelené',
  notifications_permission_denied: 'Povolenie pre notifikácie zamietnuté',
  notifications_permission_unknown: 'Povolenie ešte nebolo vyžiadané',
  notifications_request_permission: 'Vyžiadať povolenie',
  notifications_send_title: 'Odoslať notifikácie',
  notifications_last_sent: 'Posledná odoslaná',
  notifications_send_reminder: 'Pripomienka',
  notifications_send_promo: 'Promo',
  notifications_reminder_title: 'Pripomienka',
  notifications_reminder_message: 'Nezabudnite skontrolovať svoje úlohy!',
  notifications_promo_title: 'Špeciálna ponuka',
  notifications_promo_message: 'Pozrite si naše najnovšie ponuky a novinky!',
  notifications_cancel_title: 'Správa',
  notifications_open_settings: 'Nastavenia',
  notifications_cancel_all: 'Zrušiť všetky',

  // Login
  login_title: 'Vitajte',
  login_subtitle: 'Prihláste sa pre pokračovanie',
  login_email_label: 'Email',
  login_email_placeholder: 'Zadajte váš email',
  login_password_label: 'Heslo',
  login_password_placeholder: 'Zadajte vaše heslo',
  login_button: 'Prihlásiť sa',
  login_skip: 'Preskočiť',
  login_fill_test: 'Vyplniť testovací účet',
  login_biometric_label: 'Prihlásiť sa biometriou',
  login_biometric_cancelled: 'Autentifikácia zrušená',
  login_email_error_empty: 'Email je povinný',
  login_email_error_invalid: 'Neplatný formát emailu',
  login_password_error_empty: 'Heslo je povinné',
  login_password_error_short: 'Heslo musí mať aspoň 8 znakov',
  login_password_error_weak: 'Heslo musí obsahovať veľké, malé písmeno, číslicu a špeciálny znak',
  login_to_register: 'Nemáte účet? Zaregistrujte sa',

  // Register
  register_title: 'Vytvoriť účet',
  register_subtitle: 'Vyplňte údaje pre registráciu',
  register_name_label: 'Meno',
  register_name_placeholder: 'Zadajte vaše meno',
  register_email_label: 'Email',
  register_email_placeholder: 'Zadajte váš email',
  register_password_label: 'Heslo',
  register_password_placeholder: 'Zadajte vaše heslo',
  register_confirm_label: 'Potvrdiť heslo',
  register_confirm_placeholder: 'Potvrďte vaše heslo',
  register_button: 'Zaregistrovať sa',
  register_to_login: 'Už máte účet? Prihláste sa',
  register_name_error_empty: 'Meno je povinné',
  register_email_error_empty: 'Email je povinný',
  register_email_error_invalid: 'Neplatný formát emailu',
  register_password_error_empty: 'Heslo je povinné',
  register_password_error_short: 'Heslo musí mať aspoň 8 znakov',
  register_password_error_weak: 'Heslo musí obsahovať veľké, malé písmeno, číslicu a špeciálny znak',
  register_confirm_error_empty: 'Prosím potvrďte heslo',
  register_confirm_error_mismatch: 'Heslá sa nezhodujú',

  // Common
  common_loading: 'Načítavam...',
  common_error: 'Chyba',
  common_retry: 'Skúsiť znova',
  common_cancel: 'Zrušiť',
  common_ok: 'OK',
  common_save: 'Uložiť',
};
